version: "3"

networks:
    net:
        driver: bridge
volumes:
  wordpressDB:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/dboyer/data/wordpressDB
  wordpressFiles:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/dboyer/data/wordpressFiles


services:
    mysql:
        build: ./requirements/mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - ROOT_PASSWORD=${ROOT_PASSWORD}
        volumes:
            - wordpressDB:/var/lib/mysql
            - ./requirements/mariadb/tools/my.cnf:/etc/mysql/my.cnf
        networks:
            - net
    wordpress:
        build: ./requirements/wordpress
        restart: always
        ports:
            - 9000:9000
        depends_on:
            - mysql
        environment:
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - ADMIN_MAIL=${ADMIN_MAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - ADMIN_USER=${ADMIN_USER}
            - URL=${WORDPRESS_URL}
        volumes:
            - wordpressFiles:/var/www/wordpress
            - ./requirements/wordpress/tools/www.conf:/etc/php7/php-fpm.d/www.conf
        networks:
            - net
    nginx:
        build: ./requirements/nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - ./requirements/nginx/tools/nginx.conf:/etc/nginx/nginx.conf
            - type: volume
              source: wordpressFiles
              target: /var/www/wordpress
              volume:
                nocopy: true
        networks:
            - net
