version: "3"
volumes:
    wordpressDB:
    wordpressFiles:
services:
    mysql:
        build: ./mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - ROOT_PASSWORD=${ROOT_PASSWORD}
        volumes:
            - wordpressDB:/var/lib/mysql
    wordpress:
        build: ./wordpress
        restart: always
        ports:
            - 9000:9000
        depends_on:
            - mysql
        environment:
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - ADMIN_MAIL=${ADMIN_MAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - ADMIN_USER=${ADMIN_USER}
            - URL=${WORDPRESS_URL}*
        volumes:
            - wordpressFiles:/var/www/wordpress
