version: "3"
volumes:
    wordpressDB:
    wordpressFiles:
networks:
    net:
        driver: bridge
services:
    mysql:
        build: ./mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - ROOT_PASSWORD=${ROOT_PASSWORD}
        volumes:
            - wordpressDB:/var/lib/mysql
        networks:
            - net
    wordpress:
        build: ./wordpress
        restart: always
        ports:
            - 9000:9000
        depends_on:
            - mysql
        environment:
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - ADMIN_MAIL=${ADMIN_MAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - ADMIN_USER=${ADMIN_USER}
            - URL=${WORDPRESS_URL}
        volumes:
            - wordpressFiles:/var/www/wordpress
            - ./wordpress/www.conf:/etc/php7/php-fpm.d/www.conf
        networks:
            - net
    nginx:
        build: ./nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - wordpress:rw
        depends_on:
            - wordpress
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - net
